AWSTemplateFormatVersion: '2010-09-09'
Description: Enable AWS Security Hub and Security Standards

Resources:
  SecurityHub:
    Type: AWS::SecurityHub::Hub

  CISAWSFoundationsBenchmark14:
    Type: AWS::SecurityHub::Standard
    Properties:
      StandardsArn: arn:aws:securityhub:us-east-1::standards/cis-aws-foundations-benchmark/v/1.4.0


  NIST80053Rev5:
    Type: AWS::SecurityHub::Standard
    Properties:
      StandardsArn: arn:aws:securityhub:us-east-1::standards/nist-800-53/v/5.0.0


  PCIDSSv321:
    Type: AWS::SecurityHub::Standard
    Properties:
      StandardsArn: arn:aws:securityhub:us-east-1::standards/pci-dss/v/3.2.1




